[2025-04-14T15:10:52.976+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T15:10:52.988+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batdongsan_scraping.save_links scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T15:10:52.995+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batdongsan_scraping.save_links scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T15:10:52.996+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-14T15:10:53.005+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): save_links> on 2025-04-13 00:00:00+00:00
[2025-04-14T15:10:53.015+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'batdongsan_scraping', 'save_links', 'scheduled__2025-04-13T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/batdongsan_scraping_dag.py', '--cfg-path', '/tmp/tmpfk3gdffy']
[2025-04-14T15:10:53.021+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask save_links
[2025-04-14T15:10:53.017+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=182) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-14T15:10:53.021+0000] {standard_task_runner.py:72} INFO - Started process 183 to run task
[2025-04-14T15:10:53.068+0000] {task_command.py:467} INFO - Running <TaskInstance: batdongsan_scraping.save_links scheduled__2025-04-13T00:00:00+00:00 [running]> on host bc96f256ac97
[2025-04-14T15:10:53.154+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='batdongsan_scraping' AIRFLOW_CTX_TASK_ID='save_links' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-13T00:00:00+00:00'
[2025-04-14T15:10:53.155+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T15:10:53.185+0000] {SaveLinkBatdongsan.py:114} ERROR - Error scraping page 1: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:10:53.185+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 89, in driver_location
    args = [str(self.get_binary()), "--browser", browser]
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 63, in get_binary
    raise WebDriverException(f"Unsupported platform/architecture combination: {sys.platform}/{arch}")
selenium.common.exceptions.WebDriverException: Message: Unsupported platform/architecture combination: linux/aarch64


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/airflow/dags/../scripts/SaveLinkBatdongsan.py", line 89, in scrape_page
    driver = webdriver.Chrome(options=self.chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 49, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/batdongsan_scraping_dag.py", line 40, in save_links_task
    scraper.run()
  File "/opt/airflow/dags/../scripts/SaveLinkBatdongsan.py", line 206, in run
    self.scrape_all_pages()
  File "/opt/airflow/dags/../scripts/SaveLinkBatdongsan.py", line 127, in scrape_all_pages
    page_errors = self.scrape_page(page_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/../scripts/SaveLinkBatdongsan.py", line 115, in scrape_page
    error_urls.append(full_path)
                      ^^^^^^^^^
UnboundLocalError: cannot access local variable 'full_path' where it is not associated with a value
[2025-04-14T15:10:53.198+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=batdongsan_scraping, task_id=save_links, run_id=scheduled__2025-04-13T00:00:00+00:00, execution_date=20250413T000000, start_date=20250414T151052, end_date=20250414T151053
[2025-04-14T15:10:53.217+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T15:10:53.218+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task save_links (cannot access local variable 'full_path' where it is not associated with a value; 183)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 89, in driver_location
    args = [str(self.get_binary()), "--browser", browser]
                ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/selenium_manager.py", line 63, in get_binary
    raise WebDriverException(f"Unsupported platform/architecture combination: {sys.platform}/{arch}")
selenium.common.exceptions.WebDriverException: Message: Unsupported platform/architecture combination: linux/aarch64


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/airflow/dags/../scripts/SaveLinkBatdongsan.py", line 89, in scrape_page
    driver = webdriver.Chrome(options=self.chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 49, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/batdongsan_scraping_dag.py", line 40, in save_links_task
    scraper.run()
  File "/opt/airflow/dags/../scripts/SaveLinkBatdongsan.py", line 206, in run
    self.scrape_all_pages()
  File "/opt/airflow/dags/../scripts/SaveLinkBatdongsan.py", line 127, in scrape_all_pages
    page_errors = self.scrape_page(page_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/../scripts/SaveLinkBatdongsan.py", line 115, in scrape_page
    error_urls.append(full_path)
                      ^^^^^^^^^
UnboundLocalError: cannot access local variable 'full_path' where it is not associated with a value
[2025-04-14T15:10:53.252+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-14T15:10:53.275+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-14T15:10:53.276+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-14T15:21:17.585+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-14T15:21:17.601+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batdongsan_scraping.save_links scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T15:21:17.607+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batdongsan_scraping.save_links scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T15:21:17.607+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-14T15:21:17.618+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): save_links> on 2025-04-13 00:00:00+00:00
[2025-04-14T15:21:17.624+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'batdongsan_scraping', 'save_links', 'scheduled__2025-04-13T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/batdongsan_scraping_dag.py', '--cfg-path', '/tmp/tmpl_dwfn3v']
[2025-04-14T15:21:17.629+0000] {standard_task_runner.py:105} INFO - Job 2: Subtask save_links
[2025-04-14T15:21:17.629+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=212) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-14T15:21:17.631+0000] {standard_task_runner.py:72} INFO - Started process 213 to run task
[2025-04-14T15:21:17.676+0000] {task_command.py:467} INFO - Running <TaskInstance: batdongsan_scraping.save_links scheduled__2025-04-13T00:00:00+00:00 [running]> on host 932270897c9d
[2025-04-14T15:21:17.736+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='batdongsan_scraping' AIRFLOW_CTX_TASK_ID='save_links' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-13T00:00:00+00:00'
[2025-04-14T15:21:17.737+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-14T15:21:17.824+0000] {SaveLinkBatdongsan.py:104} INFO - Loaded 60334 existing links
[2025-04-14T15:21:17.826+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:19.747+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:19.804+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 1: Message: Service /home/***/.local/share/undetected_chromedriver/undetected_chromedriver unexpectedly exited. Status code was: -5

[2025-04-14T15:21:19.805+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:21.247+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:21.277+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 2: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:21.279+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:22.823+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:22.859+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 3: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:22.859+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:24.266+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:24.289+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 4: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:24.291+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:25.382+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:25.398+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 5: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:25.399+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:26.557+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:26.571+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 6: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:26.572+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:27.907+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:27.928+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 7: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:27.928+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:29.021+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:29.037+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 8: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:29.037+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:30.280+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:30.297+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 9: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:30.298+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:31.613+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:31.630+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 10: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:31.813+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:21:31.814+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 10
[2025-04-14T15:21:31.814+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:33.223+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:33.241+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 11: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:33.242+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:35.519+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:35.535+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 12: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:35.535+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:36.875+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:36.907+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 13: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:36.908+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:38.112+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:38.143+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 14: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:38.146+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:39.492+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:39.509+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 15: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:39.510+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:40.676+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:40.699+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 16: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:40.699+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:41.807+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:41.823+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 17: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:41.824+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:43.137+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:43.153+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 18: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:43.153+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:44.351+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:44.375+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 19: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:44.376+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:45.486+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:45.502+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 20: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:45.669+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:21:45.669+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 20
[2025-04-14T15:21:45.670+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:46.849+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:46.867+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 21: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:46.867+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:47.918+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:47.933+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 22: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:47.934+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:50.176+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:50.191+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 23: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:50.191+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:51.572+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:51.588+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 24: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:51.588+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:53.560+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:53.588+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 25: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:53.588+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:54.832+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:54.857+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 26: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:54.858+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:56.365+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:56.392+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 27: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:56.393+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:58.113+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:58.140+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 28: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:58.141+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:21:59.343+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:21:59.369+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 29: you cannot reuse the ChromeOptions object
[2025-04-14T15:21:59.370+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:00.567+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:00.585+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 30: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:00.785+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:22:00.785+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 30
[2025-04-14T15:22:00.785+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:02.017+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:02.037+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 31: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:02.037+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:03.262+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:03.285+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 32: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:03.286+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:04.611+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:04.630+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 33: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:04.631+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:05.858+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:05.884+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 34: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:05.885+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:07.374+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:07.391+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 35: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:07.392+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:09.093+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:09.121+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 36: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:09.122+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:10.475+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:10.497+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 37: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:10.497+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:14.858+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:14.906+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 38: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:14.908+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:16.246+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:16.278+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 39: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:16.278+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:20.012+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:20.028+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 40: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:20.189+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:22:20.190+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 40
[2025-04-14T15:22:20.190+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:21.396+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:21.433+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 41: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:21.434+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:22.655+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:22.673+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 42: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:22.673+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:24.171+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:24.202+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 43: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:24.202+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:25.567+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:25.585+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 44: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:25.587+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:26.770+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:26.792+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 45: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:26.792+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:28.889+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:28.939+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 46: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:28.941+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:30.363+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:30.388+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 47: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:30.389+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:31.645+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:31.659+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 48: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:31.660+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:32.735+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:32.753+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 49: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:32.753+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:34.164+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:34.187+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 50: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:34.345+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:22:34.346+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 50
[2025-04-14T15:22:34.346+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:35.627+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:35.654+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 51: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:35.655+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:37.094+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:37.137+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 52: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:37.138+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:38.264+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:38.282+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 53: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:38.282+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:39.706+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:39.724+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 54: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:39.725+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:40.896+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:40.951+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 55: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:40.952+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:43.202+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:43.223+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 56: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:43.223+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:44.477+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:44.496+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 57: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:44.496+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:45.716+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:45.774+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 58: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:45.776+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:47.093+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:47.111+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 59: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:47.112+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:48.266+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:48.282+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 60: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:48.437+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:22:48.437+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 60
[2025-04-14T15:22:48.438+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:49.943+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:49.971+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 61: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:49.972+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:51.273+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:51.295+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 62: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:51.296+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:53.581+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:53.613+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 63: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:53.615+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:54.971+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:54.994+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 64: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:54.996+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:56.255+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:56.276+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 65: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:56.278+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:57.626+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:57.650+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 66: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:57.651+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:22:58.923+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:22:58.942+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 67: you cannot reuse the ChromeOptions object
[2025-04-14T15:22:58.943+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:00.239+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:00.256+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 68: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:00.256+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:01.519+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:01.537+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 69: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:01.538+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:02.873+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:02.899+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 70: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:03.058+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:23:03.059+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 70
[2025-04-14T15:23:03.059+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:04.512+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:04.544+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 71: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:04.545+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:06.496+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:06.529+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 72: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:06.530+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:07.714+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:07.746+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 73: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:07.747+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:08.900+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:08.917+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 74: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:08.918+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:10.245+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:10.269+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 75: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:10.271+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:11.698+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:11.727+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 76: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:11.728+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:13.053+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:13.073+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 77: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:13.074+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:14.370+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:14.391+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 78: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:14.392+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:17.988+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 79: [Errno 2] No such file or directory: '/home/***/.local/share/undetected_chromedriver/undetected/chromedriver-linux64/chromedriver' -> '/home/***/.local/share/undetected_chromedriver/undetected_chromedriver'
[2025-04-14T15:23:17.990+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:19.537+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:19.557+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 80: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:19.732+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:23:19.733+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 80
[2025-04-14T15:23:19.733+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:21.154+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:21.177+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 81: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:21.178+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:22.560+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:22.589+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 82: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:22.589+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:23.892+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:23.911+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 83: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:23.912+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:25.330+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:25.350+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 84: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:25.351+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:26.505+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:26.537+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 85: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:26.538+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:27.935+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:27.959+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 86: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:27.961+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:29.264+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:29.307+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 87: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:29.310+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:30.566+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:30.583+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 88: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:30.584+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:31.787+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:31.807+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 89: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:31.807+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:32.984+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:33.003+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 90: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:33.180+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:23:33.180+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 90
[2025-04-14T15:23:33.180+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:34.350+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:34.384+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 91: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:34.385+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:36.443+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 92: [Errno 2] No such file or directory: '/home/***/.local/share/undetected_chromedriver/undetected/chromedriver-linux64/chromedriver' -> '/home/***/.local/share/undetected_chromedriver/undetected_chromedriver'
[2025-04-14T15:23:36.446+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:37.637+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:37.662+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 93: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:37.662+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:41.660+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:41.697+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 94: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:41.697+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:43.142+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:43.164+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 95: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:43.165+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:44.808+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 96: [Errno 2] No such file or directory: '/home/***/.local/share/undetected_chromedriver/undetected/chromedriver-linux64/chromedriver' -> '/home/***/.local/share/undetected_chromedriver/undetected_chromedriver'
[2025-04-14T15:23:44.809+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:45.942+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:45.987+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 97: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:45.988+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:48.291+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:48.326+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 98: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:48.331+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:49.505+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:49.527+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 99: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:49.528+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:50.657+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:50.679+0000] {SaveLinkBatdongsan.py:141} ERROR - Error scraping page 100: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:50.864+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:23:50.864+0000] {SaveLinkBatdongsan.py:160} INFO - Progress saved at page 100
[2025-04-14T15:23:51.062+0000] {SaveLinkBatdongsan.py:111} INFO - Saved 60334 links to /opt/***/data/batdongsan_links.txt
[2025-04-14T15:23:51.066+0000] {SaveLinkBatdongsan.py:170} INFO - Saved 100 error URLs to /opt/***/data/batdongsan_error_links.txt
[2025-04-14T15:23:51.068+0000] {SaveLinkBatdongsan.py:184} INFO - Retrying 100 error URLs...
[2025-04-14T15:23:51.070+0000] {SaveLinkBatdongsan.py:190} INFO - Retrying (1/5): https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty
[2025-04-14T15:23:51.071+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:52.263+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:52.293+0000] {SaveLinkBatdongsan.py:211} ERROR - Error fetching https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:53.373+0000] {SaveLinkBatdongsan.py:190} INFO - Retrying (2/5): https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty
[2025-04-14T15:23:53.376+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:23:54.860+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:23:54.889+0000] {SaveLinkBatdongsan.py:211} ERROR - Error fetching https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty: you cannot reuse the ChromeOptions object
[2025-04-14T15:23:58.424+0000] {SaveLinkBatdongsan.py:190} INFO - Retrying (3/5): https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty
[2025-04-14T15:23:58.443+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:24:00.227+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:24:00.267+0000] {SaveLinkBatdongsan.py:211} ERROR - Error fetching https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty: you cannot reuse the ChromeOptions object
[2025-04-14T15:24:02.976+0000] {SaveLinkBatdongsan.py:190} INFO - Retrying (4/5): https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty
[2025-04-14T15:24:02.979+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:24:04.271+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:24:04.299+0000] {SaveLinkBatdongsan.py:211} ERROR - Error fetching https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty: you cannot reuse the ChromeOptions object
[2025-04-14T15:24:06.482+0000] {SaveLinkBatdongsan.py:190} INFO - Retrying (5/5): https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty
[2025-04-14T15:24:06.484+0000] {SaveLinkBatdongsan.py:76} ERROR - Error creating WebDriver: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

[2025-04-14T15:24:07.950+0000] {patcher.py:346} INFO - patching driver executable /home/***/.local/share/undetected_chromedriver/undetected_chromedriver
[2025-04-14T15:24:08.042+0000] {SaveLinkBatdongsan.py:211} ERROR - Error fetching https://batdongsan.com.vn/nha-dat-ban/p1?gtn=7-ty&gcn=30-ty: you cannot reuse the ChromeOptions object
[2025-04-14T15:24:08.908+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-04-14T15:24:08.939+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-14T15:24:08.957+0000] {process_utils.py:132} INFO - Sending 15 to group 213. PIDs of all processes in the group: [217, 236, 237, 261, 277, 355, 361, 437, 259, 213]
[2025-04-14T15:24:08.960+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 213
[2025-04-14T15:24:08.965+0000] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-14T15:24:09.006+0000] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
  File "/home/***/.local/lib/python3.12/site-packages/***/__main__.py", line 62, in main
    args.func(args)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 56, in scheduler
    run_command_with_daemon_option(
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 59, in <lambda>
    callback=lambda: _run_scheduler_job(args),
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/scheduler_command.py", line 47, in _run_scheduler_job
    run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/scheduler_job_runner.py", line 990, in _execute
    executor.start()
  File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 392, in start
    self.impl.start()
  File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 330, in start
    worker.start()
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.12/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 80, in run
    return super().run()
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/traces/tracer.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 211, in do_work
    self.execute_work(key=key, command=command)
  File "/home/***/.local/lib/python3.12/site-packages/***/traces/tracer.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 100, in execute_work
    state = self._execute_work_in_fork(command)
  File "/home/***/.local/lib/python3.12/site-packages/***/traces/tracer.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/executors/local_executor.py", line 142, in _execute_work_in_fork
    args.func(args)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/home/***/.local/lib/python3.12/site-packages/***/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/***/dags/batdongsan_scraping_dag.py", line 40, in save_links_task
    # Use the refactored scraper with custom configuration
  File "/opt/***/dags/../scripts/SaveLinkBatdongsan.py", line 234, in run
    self.logger.info(f"Retry complete. {len(remaining_errors)} failed pages remaining in {self.error_file}.")
  File "/opt/***/dags/../scripts/SaveLinkBatdongsan.py", line 217, in retry_error_urls
    except Exception as e:
  File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-04-14T15:24:09.034+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=355, status='terminated', started='15:21:20') (355) terminated with exit code None
[2025-04-14T15:24:09.151+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-14T15:24:09.204+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=217, status='terminated', started='15:21:19') (217) terminated with exit code None
[2025-04-14T15:24:09.208+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=236, status='terminated', started='15:21:19') (236) terminated with exit code None
[2025-04-14T15:24:09.210+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=361, status='terminated', started='15:21:20') (361) terminated with exit code None
[2025-04-14T15:24:09.212+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=437, status='terminated', started='15:21:20') (437) terminated with exit code None
[2025-04-14T15:24:09.213+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=237, status='terminated', started='15:21:19') (237) terminated with exit code None
[2025-04-14T15:24:09.214+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=259, status='terminated', started='15:21:19') (259) terminated with exit code None
[2025-04-14T15:24:09.218+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=277, status='terminated', started='15:21:19') (277) terminated with exit code None
[2025-04-14T15:24:09.222+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=261, status='terminated', started='15:21:19') (261) terminated with exit code None
[2025-04-14T15:24:09.227+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=213, status='terminated', exitcode=0, started='15:21:17') (213) terminated with exit code 0
